name: CI/CD Module Pipeline

on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:
    inputs:
      browser:
        description: "Choose browser for UI tests"
        required: true
        default: "chrome"
        type: "choice"
        options:
          - chrome
          - edge

jobs:
  api_tests:
    name: Run API tests
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      - name: Restore test tools
        run: dotnet tool restore

      - name: Restore dependencies
        run: dotnet restore
        working-directory: .

      - name: Build API tests
        run: dotnet build --no-restore
        working-directory: .

      - name: Run API tests
        run: dotnet test --no-build --logger trx --results-directory TestResults --filter TestCategory=API
        continue-on-error: true

      - name: Save API tests results
        uses: actions/upload-artifact@v4
        with:
          name: api-tests-results
          path: TestResults
         
      - name: Save Log Files
        if: always()
        uses: actions/upload-artifact@v4
        with:
         name: api-logs
         path: '**/Logs/**/*.txt'
         if-no-files-found: ignore

  ui_tests:
    name: Run UI tests
    runs-on: windows-latest
    needs: api_tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      - name: Restore test tools
        run: dotnet tool restore

      - name: Restore dependencies
        run: dotnet restore
        working-directory: .

      - name: Build UI tests
        run: dotnet build --no-restore
        working-directory: .

      - name: Ensure Screenshots Directory Exists
        run: powershell -Command "New-Item -ItemType Directory -Force -Path Screenshots"

      - name: Run UI tests
        run: dotnet test --no-build --logger trx --results-directory TestResults --filter TestCategory=UI
        continue-on-error: true
        env:
           BROWSER: ${{ github.event.inputs.browser }}

      - name: Debug - List Screenshot Files
        if: always()
        run: dir Screenshots

      - name: Save UI Tests Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
         name: ui-tests-results
         path: |
          **/TestResults
          **/*.trx
         
      - name: Save Screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
         name: screenshots
         path: '**/*.png'
         if-no-files-found: ignore
         
      - name: Save Log Files
        if: always()
        uses: actions/upload-artifact@v4
        with:
         name: ui-logs
         path: '**/Logs/**/*.txt'
         if-no-files-found: ignore